version: '3.8'

services:
  appium:
    image: appium/appium:latest
    container_name: appium-server
    ports:
      - "4723:4723"
    environment:
      - RELAXED_SECURITY=true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ./app:/app
    privileged: true
    command: appium --allow-insecure chromedriver_autodownload --relaxed-security
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4723/status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  android-emulator:
    image: budtmo/docker-android:emulator_11.0
    container_name: android-emulator
    privileged: true
    ports:
      - "5555:5555"
      - "5554:5554"
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S10
      - WEB_VNC=true
      - DATAPARTITION=4096m
      - EMULATOR_TIMEOUT=300
    volumes:
      - ./app:/app
    healthcheck:
      test: ["CMD", "adb", "shell", "getprop", "sys.boot_completed"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 120s

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-runner
    depends_on:
      appium:
        condition: service_healthy
      android-emulator:
        condition: service_healthy
    environment:
      - APPIUM_HOST=appium
      - APPIUM_PORT=4723
      - DEVICE_HOST=android-emulator
      - DEVICE_PORT=5555
    volumes:
      - .:/workspace
      - ./allure-results:/workspace/allure-results
    working_dir: /workspace
    command: pytest tests/test_smoke.py -v -s --alluredir=allure-results --clean-alluredir